<template>
    <div class="openai-container">
      <h1>OpenAI API Integration in Vue.js</h1>
      <textarea 
        v-model="userInput" 
        placeholder="Enter your prompt here..." 
        rows="4" 
        cols="50">
      </textarea>
      <div class="action-buttons">
        <button @click="generateText">Generate Text</button>
        <button @click="generateImage">Generate Image</button>
      </div>
      <div v-if="generatedText" class="output-section">
        <h2>Generated Text</h2>
        <p>{{ generatedText }}</p>
      </div>
      <div v-if="generatedImage" class="output-section">
        <h2>Generated Image</h2>
        <img :src="generatedImage" alt="Image generated by OpenAI API" />
      </div>
    </div>
  </template>